language: java
os: linux
dist: trusty
addons:
  hosts:
  - jbake-builder
  hostname: jbake-builder

install: true

script:
- "./gradlew check"

after_failure:
- "./gradlew check -i --stacktrace"

matrix:
  include:
    - jdk: oraclejdk9
    - jdk: oraclejdk8
    - jdk: openjdk8
    - jdk: openjdk7
      dist: precise
    - os: osx

jobs:
  include:

  - stage: Quality Check
    jdk: oraclejdk8
    env:
    - SONAR_HOST="https://sonarcloud.io"
    - SONARORG="ancho-github"
    - GITHUB_REPO="ancho/jbake"
    script:
    - "./gradlew jacocoRootReport"
    after_success:
    - "./gradlew sonarqube -i --stacktrace"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"